# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 304120422b0291de7a2db5957133771b7bd1c38bbf427fba0188ba55a11b6f6937076c3f8c93734b415054702f3e53236033f771c888af6990b854a0c76bc97e

test:
  secret_key_base: 1b5c7e6fdd3b5a397ded94ebd419a7097de8dc2042f4a495fcb86101b3f39ae6a0004a2fc5340b185a261a1fe8e2efa2483dcbb71ceb6917d62a0c47d9eb8ceb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
